//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronic_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int OrderID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<long> Quanlity { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
