//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronic_Store.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Product
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public int BrandID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<decimal> Price { get; set; }
        [DisplayName("Image")]
        public string ProductImg { get; set; }
        
        public virtual Brand Brand { get; set; }
        
        public virtual Category Category { get; set; }
    }
}
